---
- hosts: web
  become: yes

  tasks:

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -s - \
       --write-kubeconfig-mode 644
      args:
        creates: /usr/local/bin/k3s

    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Create monitoring directory
      file:
        path: /home/ubuntu/banana-app/monitoring
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy monitoring files
      copy:
        src: /home/carrie/banana/monitoring/
        dest: /home/ubuntu/banana-app/monitoring/

    - name: Install Prometheus and Grafana
      shell: |
        export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
        bash install-monitoring.sh
      args:
        chdir: /home/ubuntu/banana-app/monitoring/
        
    - name: Create app directory
      file:
        path: /home/ubuntu/banana-app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Create k8s directory
      file:
        path: /home/ubuntu/banana-app/k8s
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
        
    
    - name: Copy k8s files
      copy:
        src: /home/carrie/banana/kubernetes/
        dest: /home/ubuntu/banana-app/k8s/


    - name: Apply 
      command: kubectl apply -f k8s/
      args:
        chdir: /home/ubuntu/banana-app/
    
    - name: Get pods
      command: kubectl get pods
      register: pods

    - debug:
        var: pods.stdout
